language: cpp
os: linux
dist: xenial
compiler: gcc

install:
  - sudo apt-get install -y qtbase5-dev qtmultimedia5-dev
  
script:
  - cd Music/
  - qmake ./Music.pro -spec linux-g++ && /usr/bin/make qmake_all
  - make
