language: cpp
os: linux
dist: xenial
compiler: gcc
sudo: required

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
  - sudo apt-get update

install:
  - sudo apt-get install qt512base qt512multimedia qt512imageformats qt512translations libpulse-dev libgl1-mesa-dev libgl1-mesa-glx -y
  - source /opt/qt512/bin/qt512-env.sh

script:
  - cd Music/
  - /opt/qt512/bin/qmake ./Music.pro -spec linux-g++ && /usr/bin/make qmake_all
  - make
  - cd pkg/
  - wget https://gist.githubusercontent.com/jonasjaguar/726b710b1d6044e57c6faa8a11680334/raw/67f29f7adaf4d2656f2020e2389143541dce3111/makdeb
  - chmod +x makdeb
  - sudo ./makedeb
  - DEBNAME=$(find . -name jagudev-music_*)
  - cp $DEBNAME ../jagudev-music_current.deb
  - cd ..
  - cd Music/
  - tar cfvz ../Music.tar.gz Music Music.desktop
  - cd ..

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

deploy:
  provider: releases
  api_key:
    secure: MqtwDjdql/bpu+a2XC7Pr8jN3OOzanhaq1jIcHCsZ9wdzSkeheKF+KWOqLgPx4cO1nkdSr2fy3Dbv4/lXwKuzdGJr5FV9waudcXtyAyQD5wMJ4RYXFHihFG5gCBVAIf+5bBJdPN6fkKGKUCwlu3xlyAYwf8zcDzGrXlKvdpLjNZVVTGoaoqxbjh8b9xW9wmnLlzA8tRzTuvQQrHuHKROVCGSNcBB/WplgZqRTKyiXxqBij0rtgwV5dgmKimyIYsMCsGxs7yRJ1tAfAzbzMWe7YXDaGj1F7d/MYKhru4bHklUxjw02mUpsbtzxp+yR61Z77YAWLaHscA6RApEuXz4sDrFh7JUra2Fzz9c+hfJzRPlf49dBVcmB7B4zOyF7bxvX3r/BIZ0pFFJihfRpbqrzB/1Mp0wP854EfBSCB/73giYHmv7A1HR+YIrNlIkBnszuKyoxm7vt4ybstVNgaf2EYzqNz+BIzQgjF1eFhudNj8giDGsL4GzsEozqM0sHf7Kt+8szvZrjbZwl4coTJSvzFR9MiszLKungbRm1Pn3FiDjzUrjen12syK8ruaTpi4owLf3Myth2mttkUlkiPq1wO8NUFsq/poebIFUjVCb4s3D8yX1OHG9jwCgWxMzM9ivsHR1Kh2CxXK/FFgZX++i1P5vQq3X+eMcghqzF/SBihA=
  file:
    - jagudev-music_current.deb
    - Music
    - Music.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: jonasjaguar/Music

notifications:
  email:
    recipients:
      - jonasjaguar@jagudev.net
    on_success: always
    on_failure: always
