language: cpp
os: linux
dist: xenial
compiler: gcc

install:
  - sudo apt-get install -y qtbase5-dev qtmultimedia5-dev libqt5multimediawidgets5 libqt5multimedia5-plugins libqt5multimedia5  
script:
  - cd Music/
  - /usr/bin/qmake ./Music.pro -spec linux-g++ && /usr/bin/make qmake_all
  - make
